default: &default
  adapter: postgis
  encoding: unicode
  host: localhost
  username: postgres
  password: <%= ENV['WANNA_CAFE_API_DATABASE_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wanna_cafe_api_development
  schema_search_path: public

test:
  <<: *default
  database: wanna_cafe_api_test

production:
  <<: *default
  database: wanna_cafe_api_production
