default: &default
  adapter: postgis
  encoding: unicode
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: quero_cafe_api_development

test:
  <<: *default
  database: quero_cafe_api_test

production:
  <<: *default
  database: quero_cafe_api_production
  username: quero_cafe_api
  password: <%= ENV['QUERO_CAFE_API_DATABASE_PASSWORD'] %>
